<a href="https://colab.research.google.com/github/kusum1984/Data_Cleaning_python/blob/main/data_cleaning1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files
uploaded = files.upload()

Saving fifa21 raw data v2.csv to fifa21 raw data v2.csv


In [3]:
df = pd.read_csv('fifa21 raw data v2.csv')

<ipython-input-3-e8a5c45769e7>:1: DtypeWarning: Columns (76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('fifa21 raw data v2.csv')


To display all columns

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
df.head()

ID               Name                      LongName  \
0  158023           L. Messi                  Lionel Messi   
1   20801  Cristiano Ronaldo  C. Ronaldo dos Santos Aveiro   
2  200389           J. Oblak                     Jan Oblak   
3  192985       K. De Bruyne               Kevin De Bruyne   
4  190871          Neymar Jr    Neymar da Silva Santos Jr.   

                                           photoUrl  \
0  https://cdn.sofifa.com/players/158/023/21_60.png   
1  https://cdn.sofifa.com/players/020/801/21_60.png   
2  https://cdn.sofifa.com/players/200/389/21_60.png   
3  https://cdn.sofifa.com/players/192/985/21_60.png   
4  https://cdn.sofifa.com/players/190/871/21_60.png   

                                           playerUrl Nationality  Age  ↓OVA  \
0  http://sofifa.com/player/158023/lionel-messi/2...   Argentina   33    93   
1  http://sofifa.com/player/20801/c-ronaldo-dos-s...    Portugal   35    92   
2  http://sofifa.com/player/200389/jan-oblak/210006/    Slovenia   27    91   
3  http://sofifa.com/player/192985/kevin-de-bruyn...     Belgium   29    91   
4  http://sofifa.com/player/190871/neymar-da-silv...      Brazil   28    91   

   POT                         Club     Contract   Positions Height Weight  \
0   93         \n\n\n\nFC Barcelona  2004 ~ 2021  RW, ST, CF  170cm   72kg   
1   92             \n\n\n\nJuventus  2018 ~ 2022      ST, LW  187cm   83kg   
2   93      \n\n\n\nAtlético Madrid  2014 ~ 2023          GK  188cm   87kg   
3   91      \n\n\n\nManchester City  2015 ~ 2023     CAM, CM  181cm   70kg   
4   91  \n\n\n\nParis Saint-Germain  2017 ~ 2022     LW, CAM  175cm   68kg   

  Preferred Foot  BOV Best Position     Joined Loan Date End    Value   Wage  \
0           Left   93            RW   1-Jul-04           NaN  €103.5M  €560K   
1          Right   92            ST  10-Jul-18           NaN     €63M  €220K   
2          Right   91            GK  16-Jul-14           NaN    €120M  €125K   
3          Right   91           CAM  30-Aug-15           NaN    €129M  €370K   
4          Right   91            LW   3-Aug-17           NaN    €132M  €270K   

  Release Clause  Attacking  Crossing  Finishing  Heading Accuracy  \
0        €138.4M        429        85         95                70   
1         €75.9M        437        84         95                90   
2        €159.4M         95        13         11                15   
3          €161M        407        94         82                55   
4        €166.5M        408        85         87                62   

   Short Passing  Volleys  Skill  Dribbling  Curve  FK Accuracy  Long Passing  \
0             91       88    470         96     93           94            91   
1             82       86    414         88     81           76            77   
2             43       13    109         12     13           14            40   
3             94       82    441         88     85           83            93   
4             87       87    448         95     88           89            81   

   Ball Control  Movement  Acceleration  Sprint Speed  Agility  Reactions  \
0            96       451            91            80       91         94   
1            92       431            87            91       87         95   
2            30       307            43            60       67         88   
3            92       398            77            76       78         91   
4            95       453            94            89       96         91   

   Balance  Power  Shot Power  Jumping  Stamina  Strength  Long Shots  \
0       95    389          86       68       72        69          94   
1       71    444          94       95       84        78          93   
2       49    268          59       78       41        78          12   
3       76    408          91       63       89        74          91   
4       83    357          80       62       81        50          84   

   Mentality  Aggression  Interceptions  Positioning  Vision  Penalt

In [6]:
df.shape

(18979, 77)

In [7]:
df.isnull()

ID   Name  LongName  photoUrl  playerUrl  Nationality    Age   ↓OVA  \
0      False  False     False     False      False        False  False  False   
1      False  False     False     False      False        False  False  False   
2      False  False     False     False      False        False  False  False   
3      False  False     False     False      False        False  False  False   
4      False  False     False     False      False        False  False  False   
...      ...    ...       ...       ...        ...          ...    ...    ...   
18974  False  False     False     False      False        False  False  False   
18975  False  False     False     False      False        False  False  False   
18976  False  False     False     False      False        False  False  False   
18977  False  False     False     False      False        False  False  False   
18978  False  False     False     False      False        False  False  False   

         POT   Club  Contract  Positions  Height  Weight  Preferred Foot  \
0      False  False     False      False   False   False           False   
1      False  False     False      False   False   False           False   
2      False  False     False      False   False   False           False   
3      False  False     False      False   False   False           False   
4      False  False     False      False   False   False           False   
...      ...    ...       ...        ...     ...     ...             ...   
18974  False  False     False      False   False   False           False   
18975  False  False     False      False   False   False           False   
18976  False  False     False      False   False   False           False   
18977  False  False     False      False   False   False           False   
18978  False  False     False      False   False   False           False   

         BOV  Best Position  Joined  Loan Date End  Value   Wage  \
0      False          False   False           True  False  False   
1      False          False   False           True  False  False   
2      False          False   False           True  False  False   
3      False          False   False           True  False  False   
4      False          False   False           True  False  False   
...      ...            ...     ...            ...    ...    ...   
18974  False          False   False           True  False  False   
18975  False          False   False           True  False  False   
18976  False          False   False           True  False  False   
18977  False          False   False           True  False  False   
18978  False          False   False           True  False  False   

       Release Clause  Attacking  Crossing  Finishing  Heading Accuracy  \
0               False      False     False      False             False   
1               False      False     False      False             False   
2               False      False     False      False             False   
3               False      False     False      False             False   
4               False      False     False      False             False   
...               ...        ...       ...        ...               ...   
18974           False      False     False      False             False   
18975           False      False     False      False             False   
18976           False      False     False      False             False   
18977           False      False     False      False             False   
18978           False      False     False      False             False   

       Short Passing  Volleys  Skill  Dribbling  Curve  FK Accuracy  \
0              False    False  False      False  False        False   
1              False    False  False      False  False        False   
2              False    False  False      False  False        False   
3              False    False  False      False  False        False   
4              False    False  False      False  Fa

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   ID                18979 non-null  int64 
 1   Name              18979 non-null  object
 2   LongName          18979 non-null  object
 3   photoUrl          18979 non-null  object
 4   playerUrl         18979 non-null  object
 5   Nationality       18979 non-null  object
 6   Age               18979 non-null  int64 
 7   ↓OVA              18979 non-null  int64 
 8   POT               18979 non-null  int64 
 9   Club              18979 non-null  object
 10  Contract          18979 non-null  object
 11  Positions         18979 non-null  object
 12  Height            18979 non-null  object
 13  Weight            18979 non-null  object
 14  Preferred Foot    18979 non-null  object
 15  BOV               18979 non-null  int64 
 16  Best Position     18979 non-null  object
 17  Joined      

Create a copy of dataFrame

In [9]:
df1=df.copy()
df1.head()

ID               Name                      LongName  \
0  158023           L. Messi                  Lionel Messi   
1   20801  Cristiano Ronaldo  C. Ronaldo dos Santos Aveiro   
2  200389           J. Oblak                     Jan Oblak   
3  192985       K. De Bruyne               Kevin De Bruyne   
4  190871          Neymar Jr    Neymar da Silva Santos Jr.   

                                           photoUrl  \
0  https://cdn.sofifa.com/players/158/023/21_60.png   
1  https://cdn.sofifa.com/players/020/801/21_60.png   
2  https://cdn.sofifa.com/players/200/389/21_60.png   
3  https://cdn.sofifa.com/players/192/985/21_60.png   
4  https://cdn.sofifa.com/players/190/871/21_60.png   

                                           playerUrl Nationality  Age  ↓OVA  \
0  http://sofifa.com/player/158023/lionel-messi/2...   Argentina   33    93   
1  http://sofifa.com/player/20801/c-ronaldo-dos-s...    Portugal   35    92   
2  http://sofifa.com/player/200389/jan-oblak/210006/    Slovenia   27    91   
3  http://sofifa.com/player/192985/kevin-de-bruyn...     Belgium   29    91   
4  http://sofifa.com/player/190871/neymar-da-silv...      Brazil   28    91   

   POT                         Club     Contract   Positions Height Weight  \
0   93         \n\n\n\nFC Barcelona  2004 ~ 2021  RW, ST, CF  170cm   72kg   
1   92             \n\n\n\nJuventus  2018 ~ 2022      ST, LW  187cm   83kg   
2   93      \n\n\n\nAtlético Madrid  2014 ~ 2023          GK  188cm   87kg   
3   91      \n\n\n\nManchester City  2015 ~ 2023     CAM, CM  181cm   70kg   
4   91  \n\n\n\nParis Saint-Germain  2017 ~ 2022     LW, CAM  175cm   68kg   

  Preferred Foot  BOV Best Position     Joined Loan Date End    Value   Wage  \
0           Left   93            RW   1-Jul-04           NaN  €103.5M  €560K   
1          Right   92            ST  10-Jul-18           NaN     €63M  €220K   
2          Right   91            GK  16-Jul-14           NaN    €120M  €125K   
3          Right   91           CAM  30-Aug-15           NaN    €129M  €370K   
4          Right   91            LW   3-Aug-17           NaN    €132M  €270K   

  Release Clause  Attacking  Crossing  Finishing  Heading Accuracy  \
0        €138.4M        429        85         95                70   
1         €75.9M        437        84         95                90   
2        €159.4M         95        13         11                15   
3          €161M        407        94         82                55   
4        €166.5M        408        85         87                62   

   Short Passing  Volleys  Skill  Dribbling  Curve  FK Accuracy  Long Passing  \
0             91       88    470         96     93           94            91   
1             82       86    414         88     81           76            77   
2             43       13    109         12     13           14            40   
3             94       82    441         88     85           83            93   
4             87       87    448         95     88           89            81   

   Ball Control  Movement  Acceleration  Sprint Speed  Agility  Reactions  \
0            96       451            91            80       91         94   
1            92       431            87            91       87         95   
2            30       307            43            60       67         88   
3            92       398            77            76       78         91   
4            95       453            94            89       96         91   

   Balance  Power  Shot Power  Jumping  Stamina  Strength  Long Shots  \
0       95    389          86       68       72        69          94   
1       71    444          94       95       84        78          93   
2       49    268          59       78       41        78          12   
3       76    408          91       63       89        74          91   
4       83    357          80       62       81        50          84   

   Mentality  Aggression  Interceptions  Positioning  Vision  Penalt

****Data cleaning****


In [10]:
df.ID

0        158023
1         20801
2        200389
3        192985
4        190871
          ...  
18974    247223
18975    258760
18976    252757
18977    243790
18978    252520
Name: ID, Length: 18979, dtype: int64

**IDs of player**

In [11]:
df1['ID'].dtype

dtype('int64')

In [12]:
df1['ID'].unique()

array([158023,  20801, 200389, ..., 252757, 243790, 252520])

**A/W**

In [13]:
df1['A/W'].dtype

dtype('O')

In [14]:
df1['A/W'].unique()

array(['Medium', 'High', 'Low'], dtype=object)

In [15]:
df1['Acceleration'].dtype

dtype('int64')

In [16]:
df1['Acceleration'].unique()

array([91, 87, 43, 77, 94, 56, 96, 38, 72, 95, 60, 42, 54, 79, 89, 64, 66,
       51, 73, 57, 80, 86, 85, 78, 40, 82, 76, 65, 68, 90, 48, 46, 88, 70,
       83, 84, 93, 52, 74, 92, 55, 58, 59, 67, 81, 62, 44, 71, 69, 50, 53,
       45, 49, 75, 41, 61, 63, 35, 47, 34, 36, 37, 39, 30, 97, 31, 33, 32,
       27, 28, 26, 29, 25, 17, 19, 24, 15, 23, 21, 20, 22, 16, 18, 13, 14])

In [17]:
df1['Age'].dtype

dtype('int64')

In [18]:
df1['Age'].unique()

array([33, 35, 27, 29, 28, 31, 21, 34, 32, 25, 26, 30, 20, 24, 22, 23, 19,
       38, 42, 36, 37, 18, 17, 39, 40, 41, 16, 43, 53])

In [19]:
df1['Aggression'].dtype

dtype('int64')

In [20]:
df1['Aggression'].unique()

array([44, 63, 34, 76, 51, 81, 27, 62, 43, 83, 75, 91, 23, 29, 90, 65, 59,
       89, 48, 38, 25, 87, 54, 60, 73, 74, 69, 85, 70, 86, 32, 40, 31, 77,
       84, 80, 78, 79, 71, 56, 42, 30, 61, 58, 28, 82, 46, 52, 36, 92, 55,
       35, 67, 37, 72, 57, 50, 64, 39, 47, 20, 68, 15, 66, 33, 93, 88, 22,
       24, 45, 17, 18, 26, 21, 11, 41, 53, 19, 12, 49, 94, 16, 95, 13, 14,
       96, 10,  9])

In [21]:
df1['Agility'].dtype

dtype('int64')

In [22]:
df1['Agility'].unique()

array([91, 87, 67, 78, 96, 77, 40, 92, 37, 61, 93, 51, 79, 84, 94, 82, 60,
       69, 47, 52, 63, 74, 59, 66, 86, 85, 57, 55, 76, 75, 73, 62, 72, 90,
       68, 64, 80, 56, 48, 83, 41, 81, 54, 88, 33, 65, 49, 71, 89, 45, 70,
       43, 50, 32, 42, 39, 58, 36, 34, 53, 46, 95, 44, 38, 21, 29, 35, 31,
       19, 26, 30, 22, 28, 24, 25, 23, 27, 14, 18, 15, 20])

In [23]:
df1['Attacking'].dtype

dtype('int64')

In [24]:
df1['Attacking'].unique()

array([429, 437,  95, 407, 408, 423, 392, 114, 118, 316, 410, 349,  86,
       119, 426, 374, 411, 360, 328, 383, 405, 123, 420, 224, 388, 397,
       425, 373, 365, 371, 311, 396, 345, 399, 400,  78, 280, 330, 403,
       379, 380,  94, 394, 419, 339, 293, 344, 390,  84, 359, 372, 377,
       346, 389, 386, 308, 277, 382, 368, 402, 292, 298, 366, 352, 363,
       322, 361,  91, 364, 341, 385, 355, 305, 321, 262,  93, 375, 387,
       356, 253, 285, 391, 353, 367,  90, 295, 378, 256, 338, 331,  69,
       105,  85, 358, 343, 319, 271, 113, 350, 406, 340, 393, 247, 334,
       351, 342, 302, 329, 354,  98, 301, 115, 384, 208,  72, 376,  92,
       258, 362,  74, 417,  99, 263,  88, 279, 101, 395, 100,  81,  87,
        55, 310,  82, 117, 409, 318, 323, 248, 315, 381, 348, 327, 309,
       130, 283, 336, 369, 106, 252, 320, 290, 370, 126, 251, 108, 335,
       297, 284,  80,  75, 357, 270,  97, 306, 337,  73, 286, 325, 326,
       324, 333, 103, 259, 273, 313, 296,  61, 312, 347, 401, 30

In [25]:
df1['BOV'].dtype

dtype('int64')

In [26]:
df1['BOV'].unique()

array([93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77,
       76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60,
       59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48])

In [27]:
df1['Balance'].dtype

dtype('int64')

In [28]:
df1['Balance'].unique()

array([95, 71, 49, 76, 83, 82, 91, 37, 43, 53, 86, 66, 45, 35, 69, 94, 92,
       84, 90, 48, 73, 36, 41, 93, 74, 60, 79, 65, 78, 61, 57, 50, 68, 51,
       54, 77, 81, 39, 75, 58, 87, 85, 63, 38, 88, 67, 72, 62, 80, 44, 46,
       42, 55, 40, 70, 32, 89, 52, 59, 47, 64, 27, 56, 30, 31, 25, 34, 29,
       24, 96, 33, 28, 20, 23, 22, 26, 21, 17, 97, 19, 12, 18])

In [29]:
df1['Ball Control'].dtype

dtype('int64')

In [30]:
df1['Ball Control'].unique()

array([96, 92, 30, 95, 88, 89, 90, 77, 79, 23, 46, 83, 80, 85, 94, 40, 84,
       16, 74, 91, 87, 82, 78, 19, 61, 22, 34, 38, 81, 25, 86, 76, 69, 28,
       93, 75, 35, 60, 63, 73, 18, 71, 15, 21, 72, 14, 65, 20, 24, 27, 70,
       33, 17, 62, 64,  9, 68, 67, 32, 26, 66, 52, 11, 57, 58, 29, 12, 37,
       10, 36, 13, 31, 55, 59, 39, 54, 56, 48, 44, 51, 50, 47, 49, 53,  5,
       42,  8, 45, 43, 41,  7])

In [31]:
df1['Base Stats'].dtype

dtype('int64')

In [32]:
df1['Base Stats'].unique()

array([466, 464, 489, 485, 451, 457, 470, 490, 484, 455, 469, 463, 468,
       497, 442, 439, 473, 452, 498, 449, 477, 401, 446, 447, 465, 430,
       461, 422, 476, 460, 453, 467, 471, 399, 424, 441, 459, 438, 437,
       454, 428, 445, 431, 474, 421, 435, 448, 475, 403, 444, 443, 419,
       405, 420, 423, 396, 388, 482, 478, 385, 394, 480, 433, 450, 462,
       456, 436, 434, 429, 400, 440, 425, 410, 458, 398, 413, 373, 406,
       408, 472, 426, 407, 432, 427, 415, 481, 417, 372, 380, 418, 383,
       414, 409, 412, 411, 386, 362, 402, 390, 404, 391, 416, 375, 389,
       361, 397, 366, 392, 393, 382, 368, 387, 352, 376, 384, 378, 379,
       341, 354, 369, 395, 357, 381, 377, 344, 360, 370, 338, 333, 367,
       363, 349, 355, 345, 358, 348, 374, 351, 343, 342, 353, 321, 350,
       365, 364, 371, 327, 331, 359, 347, 356, 339, 319, 317, 335, 346,
       329, 315, 324, 322, 325, 332, 336, 337, 330, 316, 313, 306, 307,
       328, 310, 340, 308, 318, 334, 301, 289, 302, 320, 323, 32

In [33]:
df1['Best Position'].dtype

dtype('O')

In [34]:
df1['Best Position'].unique()

array(['RW', 'ST', 'GK', 'CAM', 'LW', 'CB', 'CDM', 'CF', 'CM', 'RB', 'LB',
       'LM', 'RM', 'LWB', 'RWB'], dtype=object)

In [35]:
df1['Club'].dtype

dtype('O')

In [36]:
df1['Club'].unique()

array(['\n\n\n\nFC Barcelona', '\n\n\n\nJuventus',
       '\n\n\n\nAtlético Madrid', '\n\n\n\nManchester City',
       '\n\n\n\nParis Saint-Germain', '\n\n\n\nFC Bayern München',
       '\n\n\n\nLiverpool', '\n\n\n\nReal Madrid', '\n\n\n\nChelsea',
       '\n\n\n\nTottenham Hotspur', '\n\n\n\nInter', '\n\n\n\nNapoli',
       '\n\n\n\nBorussia Dortmund', '\n\n\n\nManchester United',
       '\n\n\n\nArsenal', '\n\n\n\nLazio', '\n\n\n\nLeicester City',
       '\n\n\n\nBorussia Mönchengladbach', '\n\n\n\nReal Sociedad',
       '\n\n\n\nAtalanta', '\n\n\n\nOlympique Lyonnais', '\n\n\n\nMilan',
       '\n\n\n\nVillarreal CF', '\n\n\n\nRB Leipzig', '\n\n\n\nCagliari',
       '\n\n\n\nAjax', '\n\n\n\nSL Benfica', '\n\n\n\nAS Monaco',
       '\n\n\n\nWolverhampton Wanderers', '\n\n\n\nEverton',
       '\n\n\n\nFiorentina', '\n\n\n\nFC Porto', '\n\n\n\nRC Celta',
       '\n\n\n\nTorino', '\n\n\n\nSevilla FC', '\n\n\n\nGrêmio',
       '\n\n\n\nReal Betis', '\n\n\n\nRoma', '\n\n\n\nNewcastle Unite

In [37]:
df1['Club'] = df1['Club'].str.strip()

In [38]:
df1['Club'].unique()

array(['FC Barcelona', 'Juventus', 'Atlético Madrid', 'Manchester City',
       'Paris Saint-Germain', 'FC Bayern München', 'Liverpool',
       'Real Madrid', 'Chelsea', 'Tottenham Hotspur', 'Inter', 'Napoli',
       'Borussia Dortmund', 'Manchester United', 'Arsenal', 'Lazio',
       'Leicester City', 'Borussia Mönchengladbach', 'Real Sociedad',
       'Atalanta', 'Olympique Lyonnais', 'Milan', 'Villarreal CF',
       'RB Leipzig', 'Cagliari', 'Ajax', 'SL Benfica', 'AS Monaco',
       'Wolverhampton Wanderers', 'Everton', 'Fiorentina', 'FC Porto',
       'RC Celta', 'Torino', 'Sevilla FC', 'Grêmio', 'Real Betis', 'Roma',
       'Newcastle United', 'Eintracht Frankfurt', 'Valencia CF',
       'Medipol Başakşehir FK', 'Inter Miami', 'Bayer 04 Leverkusen',
       'Levante UD', 'Crystal Palace', 'Athletic Club de Bilbao',
       'Shanghai SIPG FC', 'VfL Wolfsburg',
       'Guangzhou Evergrande Taobao FC', 'Al Shabab',
       'Olympique de Marseille', 'Los Angeles FC',
       'Beijing Sino

In [39]:
df1['Composure'].dtype

dtype('int64')

In [40]:
df1['Composure'].unique()

array([96, 95, 68, 91, 93, 88, 90, 65, 84, 70, 66, 80, 85, 69, 82, 89, 81,
       87, 83, 86, 67, 92, 94, 57, 78, 79, 75, 45, 61, 76, 58, 62, 77, 74,
       59, 55, 48, 40, 64, 73, 39, 71, 72, 63, 60, 52, 53, 56, 44, 54, 41,
       32, 49, 46, 31, 51, 50, 25, 18, 38, 30, 24, 21, 36, 33, 26, 23, 47,
       22, 28, 34, 35, 37, 43, 27, 12, 42, 17, 29, 13, 19, 14, 16, 20, 15])

In [41]:
df1['Contract'].dtype

dtype('O')

In [42]:
df1['Contract'].unique()

array(['2004 ~ 2021', '2018 ~ 2022', '2014 ~ 2023', '2015 ~ 2023',
       '2017 ~ 2022', '2017 ~ 2023', '2018 ~ 2024', '2014 ~ 2022',
       '2018 ~ 2023', '2016 ~ 2023', '2013 ~ 2023', '2011 ~ 2023',
       '2009 ~ 2022', '2005 ~ 2021', '2011 ~ 2021', '2015 ~ 2022',
       '2017 ~ 2024', '2010 ~ 2024', '2012 ~ 2021', '2019 ~ 2024',
       '2015 ~ 2024', '2017 ~ 2025', '2020 ~ 2025', '2019 ~ 2023',
       '2008 ~ 2023', '2015 ~ 2021', '2020 ~ 2022', '2012 ~ 2022',
       '2016 ~ 2025', '2013 ~ 2022', '2011 ~ 2022', '2012 ~ 2024',
       '2016 ~ 2021', '2012 ~ 2023', '2008 ~ 2022', '2019 ~ 2022',
       '2017 ~ 2021', '2013 ~ 2024', '2020 ~ 2024', '2010 ~ 2022',
       '2020 ~ 2021', '2011 ~ 2024', '2020 ~ 2023', '2014 ~ 2024',
       '2013 ~ 2026', '2016 ~ 2022', '2010 ~ 2021', '2013 ~ 2021',
       '2019 ~ 2025', '2018 ~ 2025', '2016 ~ 2024', '2018 ~ 2021',
       '2009 ~ 2024', '2007 ~ 2022', 'Jun 30, 2021 On Loan',
       '2009 ~ 2021', '2019 ~ 2021', '2019 ~ 2026', 'Free', '2012 ~ 

In [43]:



# Extract valid date ranges
df1['start_date'] = df1['Contract'].str.extract(r'(\d{4}) ~')
df1['end_date'] = df1['Contract'].str.extract(r'~ (\d{4})')

# Handle cases with 'On Loan' or 'Free'
df1.loc[df1['Contract'].str.contains('On Loan'), ['start_date', 'end_date']] = np.nan
df1.loc[df1['Contract'].str.contains('Free'), ['start_date', 'end_date']] = np.nan

# Convert columns to datetime format
df1['start_date'] = pd.to_numeric(df1['start_date'], errors='coerce')
df1['end_date'] = pd.to_numeric(df1['end_date'], errors='coerce')
df1['contract Lenght(years)'] = ( df1['end_date']- df1['start_date'])
# Convert float values to integers
df1['start_date'] = df1['start_date'].astype('Int64')
df1['end_date'] = df1['end_date'].astype('Int64')
df1['contract Lenght(years)'] = df1['contract Lenght(years)'].astype('Int64')
# Display the cleaned DataFrame
print(df1[['Contract', 'start_date', 'end_date','contract Lenght(years)']])



          Contract  start_date  end_date  contract Lenght(years)
0      2004 ~ 2021        2004      2021                      17
1      2018 ~ 2022        2018      2022                       4
2      2014 ~ 2023        2014      2023                       9
3      2015 ~ 2023        2015      2023                       8
4      2017 ~ 2022        2017      2022                       5
...            ...         ...       ...                     ...
18974  2018 ~ 2022        2018      2022                       4
18975  2020 ~ 2021        2020      2021                       1
18976  2019 ~ 2020        2019      2020                       1
18977  2020 ~ 2022        2020      2022                       2
18978  2019 ~ 2023        2019      2023                       4

[18979 rows x 4 columns]


In [44]:
df1.sample(2)

ID     Name     LongName  \
4615  199692  H. Mier   Hiram Mier   
3055  246242   B. Dia  Boulaye Dia   

                                              photoUrl  \
4615  https://cdn.sofifa.com/players/199/692/21_60.png   
3055  https://cdn.sofifa.com/players/246/242/21_60.png   

                                              playerUrl Nationality  Age  \
4615  http://sofifa.com/player/199692/hiram-mier/210...      Mexico   30   
3055  http://sofifa.com/player/246242/boulaye-dia/21...      France   23   

      ↓OVA  POT            Club     Contract Positions Height Weight  \
4615    70   70     Guadalajara  2019 ~ 2021        CB  182cm   74kg   
3055    73   80  Stade de Reims  2018 ~ 2022        ST  180cm   75kg   

     Preferred Foot  BOV Best Position     Joined Loan Date End  Value  Wage  \
4615          Right   70            CB   1-Jan-19           NaN  €1.3M  €22K   
3055          Right   75            ST  13-Jul-18           NaN    €6M  €20K   

     Release Clause  Attacking  Crossing  Finishing  Heading Accuracy  \
4615          €2.4M        259        49         37                72   
3055         €12.1M        310        36         76                69   

      Short Passing  Volleys  Skill  Dribbling  Curve  FK Accuracy  \
4615             67       34    242         56     41           35   
3055             65       64    279         75     48           42   

      Long Passing  Ball Control  Movement  Acceleration  Sprint Speed  \
4615            55            55       314            50            67   
3055            41            73       346            74            78   

      Agility  Reactions  Balance  Power  Shot Power  Jumping  Stamina  \
4615       66         70       61    313          53       73       67   
3055       65         68       61    362          76       70       71   

      Strength  Long Shots  Mentality  Aggression  Interceptions  Positioning  \
4615        73          47        286          65             71           45   
3055        80          65        278          59             22           74   

      Vision  Penalties  Composure  Defending  Marking  Standing Tackle  \
4615      56         49         62        213       70               72   
3055      56         67         56         59       28               17   

      Sliding Tackle  Goalkeeping  GK Diving  GK Handling  GK Kicking  \
4615              71           59         12           12           7   
3055              14           60         11           10          15   

      GK Positioning  GK Reflexes  Total Stats  Base Stats  W/F  SM     A/W  \
4615              15           13         1686         358  3 ★  2★     Low   
3055              14           10         1694         372  3 ★  3★  Medium   

       D/W   IR  PAC  SHO  PAS  DRI  DEF  PHY Hits  start_date  end_date  \
4615  High  1 ★   59   43   57   58   71   70   12        2019      2021   
3055  High  1 ★   76   73   52   72   26   73   34        2018      2022   

      contract Lenght(years)  
4615                       2  
3055                       4

In [45]:
df1['Crossing'].dtype


dtype('int64')

In [46]:
df1['Crossing'].unique()

array([85, 84, 13, 94, 71, 79, 17, 78, 18, 53, 76, 58, 14, 15, 75, 66, 70,
       68, 91, 82, 20, 12, 30, 77, 88, 83, 93, 90, 87, 81, 73, 11, 54, 62,
       86, 80, 55, 42, 57, 65, 63, 64, 52, 40, 69, 47, 60,  9, 16, 44, 72,
       50, 56, 46, 89, 34, 45, 74, 49, 67, 24, 35, 36, 61, 19, 27, 25, 10,
       51, 38, 43, 59, 39, 48, 23,  8, 28, 92, 41, 29, 32, 22, 26, 37, 33,
       31, 21,  7,  6])

In [47]:
df1['Curve'].dtype

dtype('int64')

In [48]:
df1['Curve'].unique()

array([93, 81, 13, 85, 88, 79, 83, 19, 18, 60, 76, 63, 14, 74, 77, 49, 15,
       80, 12, 28, 86, 84, 82, 61, 71, 11, 66, 16, 89, 70, 21, 46, 78, 67,
       58, 65, 48, 34, 90, 59, 55, 87, 62,  9, 56, 36, 30, 32, 73, 69, 68,
       75, 45, 10, 72, 64, 41, 23, 47, 20, 51, 25, 44, 17, 54, 57, 53, 33,
       40, 50, 39, 35, 52, 42, 37, 43, 26, 31, 92, 91, 29, 94, 27, 38, 22,
       24,  8,  6,  7,  5,  4])

In [49]:
df1['D/W'].dtype

dtype('O')

In [50]:
df1['D/W'].unique()

array(['Low', 'Medium', 'High'], dtype=object)

In [51]:
df1['DEF'].dtype

dtype('int64')

In [52]:
df1['DEF'].unique()

array([38, 35, 52, 64, 36, 43, 45, 51, 39, 91, 44, 86, 48, 57, 40, 88, 33,
       81, 63, 47, 53, 89, 71, 37, 80, 68, 85, 61, 90, 83, 49, 56, 58, 82,
       87, 79, 66, 55, 78, 32, 50, 76, 77, 70, 75, 41, 29, 73, 65, 59, 84,
       54, 72, 46, 42, 69, 34, 31, 30, 74, 24, 62, 25, 20, 26, 60, 27, 23,
       28, 67, 22, 19, 18, 21, 17, 15, 16, 12])

In [53]:
df1['DRI'].dtype

dtype('int64')

In [54]:
df1['DRI'].unique()

array([95, 89, 90, 88, 94, 85, 91, 71, 72, 86, 73, 81, 84, 92, 80, 68, 77,
       87, 60, 83, 78, 64, 67, 79, 69, 66, 65, 70, 82, 75, 61, 74, 54, 76,
       49, 63, 59, 62, 56, 55, 50, 57, 58, 52, 53, 51, 48, 47, 46, 39, 44,
       43, 36, 40, 45, 41, 37, 34, 35, 42, 32, 38, 31, 33, 30, 29, 28, 25,
       27])

In [55]:
df1['Defending'].dtype

dtype('int64')

In [56]:
df1['Defending'].unique()

array([ 91,  84,  57, 186,  94,  96, 122,  50, 100,  48, 272, 259,  54,
        38,  89, 263,  83, 147, 264, 245, 120,  52, 130, 267, 205, 162,
       105, 241, 148, 248, 266, 194, 258, 117, 166,  56, 249,  92,  45,
       214, 140,  99, 150,  59, 251, 262, 243, 195, 160,  40, 114, 236,
       244, 231,  80, 123, 253, 132, 103, 257, 261,  98,  78, 209, 229,
       230,  60, 101, 206, 242, 138,  61, 256, 171, 260, 226, 224,  44,
       131, 113, 240,  77, 232, 225, 109, 228, 247,  93, 121, 238, 111,
       128, 188, 173, 250, 255,  41, 144, 239, 217, 106, 165, 246, 235,
       126, 118, 203, 234, 135, 215, 175, 192, 108,  39,  33, 151, 156,
       174,  47, 216, 237, 102, 227, 161, 233,  67, 213,  75, 212,  36,
       254, 196,  88,  81, 134,  53, 155, 223,  43, 125,  46,  51, 137,
        71,  95,  35, 208, 110, 170,  87, 107,  55, 204, 177,  69, 152,
       163,  37, 181, 252, 159, 133, 124, 207,  82,  97,  65,  42,  79,
       104, 211, 129,  49, 157, 153, 185, 189, 146,  86, 112,  7

In [57]:
df1['Dribbling'].dtype

dtype('int64')

In [58]:
df1['Dribbling'].unique()

array([96, 88, 12, 95, 85, 90, 27, 92, 21, 70, 91, 69, 13, 30, 87, 65, 79,
       83, 23, 80, 18, 93, 77, 63, 76, 16, 59, 81, 11, 84, 10, 75, 78, 55,
       15, 86, 66, 67, 28, 57, 64, 82, 62, 19, 53, 72, 50, 26, 43, 89, 73,
       20, 14, 68, 71, 74, 22, 54, 56, 61,  9, 24, 60, 25,  8, 17, 47, 58,
       46, 42, 51, 52, 49, 44, 35, 48, 39, 29, 40, 45, 34, 31, 33, 38, 41,
       32,  7, 37, 36,  5,  6])

In [59]:
df1['FK Accuracy'].dtype

dtype('int64')

In [60]:
df1['FK Accuracy'].unique()

array([94, 76, 14, 83, 89, 85, 69, 18, 63, 12, 70, 64, 74, 20, 11, 73, 49,
       61, 88, 68, 28, 79, 84, 48, 67, 38, 87, 53, 65, 15, 31, 78, 82, 10,
       51, 59, 19, 47, 52, 57, 43, 13, 77, 54, 75, 86, 55, 30, 62, 32, 58,
       93,  8, 66, 71, 81, 92, 44, 17, 60, 40, 16, 72, 46, 35, 45, 29, 21,
       56, 80, 24, 22, 39, 42, 26, 41,  9, 37, 27, 50, 33, 25, 36, 91, 34,
       23,  7,  6, 90,  5])

In [61]:
df1['Finishing'].dtype

dtype('int64')

In [62]:
df1['Finishing'].unique()

array([95, 11, 82, 87, 94, 91, 13, 14, 52, 90, 64, 88, 65, 85, 66, 84, 10,
       22, 76, 81, 56, 79, 57, 45, 77, 63, 86, 80, 15, 33, 67, 12, 72, 92,
       93, 51, 46, 60, 75, 55, 73, 83, 50, 42, 39, 40,  9, 68, 48, 37, 70,
       78, 69,  8, 53, 89, 25, 62, 71, 74, 44, 26, 19, 32, 18, 61, 58, 30,
       54, 36, 29, 16, 38, 59, 27, 34, 47, 20, 31, 49, 43, 41, 28,  5,  7,
        6, 21, 17, 35, 23, 24,  4,  3])

In [63]:
df1['GK Diving'].dtype

dtype('int64')

In [64]:
df1['GK Diving'].unique()

array([ 6,  7, 87, 15,  9, 14, 86, 13, 88, 10, 84, 11,  8,  5, 12, 90,  3,
       27, 89, 80, 16, 85,  2, 82, 79, 83,  4, 81, 77, 18, 78, 17, 75, 74,
       76, 73, 71, 72, 52, 68, 70, 54, 69, 32, 66, 65, 67, 61, 22, 64, 23,
       40, 63, 55, 19, 50, 62, 58, 60, 59, 56, 57, 53, 51, 49, 46, 48, 47,
       45])

In [65]:
df1['GK Handling'].dtype

dtype('int64')

In [66]:
df1['GK Handling'].unique()

array([11, 92, 13,  9,  6, 14, 88,  5, 85, 10, 89, 87,  8, 15, 12,  4, 82,
       81,  3,  7, 25, 86, 83,  2, 80, 16, 77, 79, 78, 76, 84, 75, 72, 74,
       71, 69, 73, 70, 67, 68, 65, 61, 62, 64, 41, 63, 66, 33, 22, 17, 57,
       18, 54, 55, 59, 49, 19, 40, 60, 58, 43, 45, 53, 47, 56, 51, 52, 50,
       48, 46])

In [67]:
df1['GK Kicking'].dtype

dtype('int64')

In [68]:
df1['GK Kicking'].unique()

array([15, 78,  5, 12,  9, 85,  7, 88, 13, 16, 74, 91,  6, 10,  4, 93, 11,
       73, 14, 75,  2, 31, 68, 76,  8, 80, 82,  3, 87, 72, 83, 77, 79, 81,
       69, 71, 20, 67, 70, 64, 65, 63, 44, 60, 84, 54, 48, 61, 18, 66, 17,
       59, 62, 90, 43, 38, 58, 57, 28, 40, 53, 23, 47, 46, 19, 51, 55, 52,
       56, 22, 30, 25, 42, 35, 21, 49, 50, 36, 45])

In [69]:
df1['GK Positioning'].dtype

dtype('int64')

In [70]:
df1['GK Positioning'].unique()

array([14, 90, 10, 15,  8, 11, 91, 88,  7, 12, 85, 86,  5, 89, 13,  6, 82,
        4,  9, 87, 33, 84, 16, 83,  2,  3, 79, 81, 80, 76, 78, 19, 77, 17,
       75, 74, 73, 71, 18, 72, 70, 69, 66, 68, 40, 64, 20, 32, 67, 62, 65,
       63, 24, 23, 50, 55, 58, 51, 59, 56, 61, 57, 60, 46, 54, 53, 52, 47,
       49, 48, 43, 45, 42, 38, 44, 41])

In [71]:
df1['GK Reflexes'].dtype

dtype('int64')

In [72]:
df1['GK Reflexes'].unique()

array([ 8, 11, 90, 13, 10, 14, 89,  6, 12, 88,  7,  9, 15,  5,  3, 37, 85,
       86,  4, 16, 82, 83, 84, 87, 78, 80, 20, 18, 79, 81, 19, 77, 17,  2,
       74, 71, 76, 73, 75, 72, 69, 46, 66, 51, 70, 34, 67, 23, 68, 45, 65,
       21, 59, 54, 47, 61, 64, 63, 62, 60, 58, 56, 57, 55, 53, 50, 52, 49,
       48, 44])

In [73]:
df1['Goalkeeping'].dtype

dtype('int64')

In [74]:
df1['Goalkeeping'].unique()

array([ 54,  58, 437,  56,  59,  51,  62, 439,  42,  67, 420, 440,  41,
        46,  63,  60,  26, 435, 424,  43,  45,  52,  50,  47,  53,  44,
       418,  15,  48, 416, 153, 413,  65,  64,  20, 423,  49,  55,  66,
        40,  57, 421,  13,  39,  61, 419,  21, 409,  37, 406, 410,  36,
       408,  34,  29, 405, 403, 402, 407,  16,  69, 391, 401, 398, 400,
        22,  68, 396,  38,  78,  73, 399, 390, 393, 395, 397,  80,  70,
       389, 394, 388,  27,  30,  75,  71, 386,  74, 378, 385, 384, 380,
       392, 381,  10, 387, 383, 375, 382,  19, 379,  24, 369, 356, 368,
       373, 370, 372,  72, 374, 376, 364,  25, 367,  17, 377, 371, 365,
       352, 362, 359, 363, 366,  82,  35, 361, 358,  76, 294,  83, 357,
       360, 355, 354,  77, 229, 350, 353, 347, 351,  32, 349, 169, 346,
       348, 343, 345, 339, 342,  33, 341,  28, 119, 337, 338, 340, 344,
       335,  98, 324, 248, 334, 298, 336, 328, 331, 321, 332,  81,  79,
       333, 278, 329, 261, 325,  31, 327, 330, 322, 305, 326, 28

In [75]:
df1['Heading Accuracy'].dtype

dtype('int64')

In [76]:
df1['Heading Accuracy'].unique()

array([70, 90, 15, 55, 62, 85, 59, 19, 73, 11, 87, 84, 80, 13, 25, 91, 92,
       78, 46, 54, 72, 64, 14, 10, 61, 58, 83, 38, 69, 51, 67, 86, 75, 68,
       16, 81, 21, 79, 53, 65, 82, 12, 42, 48, 88, 66, 76, 74, 52, 23, 40,
       49, 60, 44, 20, 37, 71, 17, 45, 77, 50, 63, 43, 39, 57, 56, 47, 24,
       18, 31, 28, 35, 34, 41, 36, 93,  7, 30, 89,  8, 26, 33, 27, 32, 22,
       29,  9,  5,  6])

In [77]:
df1['Height'].dtype

dtype('O')

In [78]:
df1['Height'].unique()

array(['170cm', '187cm', '188cm', '181cm', '175cm', '184cm', '191cm',
       '178cm', '193cm', '185cm', '199cm', '173cm', '168cm', '176cm',
       '177cm', '183cm', '180cm', '189cm', '179cm', '195cm', '172cm',
       '182cm', '186cm', '192cm', '165cm', '194cm', '167cm', '196cm',
       '163cm', '190cm', '174cm', '169cm', '171cm', '197cm', '200cm',
       '166cm', '6\'2"', '164cm', '198cm', '6\'3"', '6\'5"', '5\'11"',
       '6\'4"', '6\'1"', '6\'0"', '5\'10"', '5\'9"', '5\'6"', '5\'7"',
       '5\'4"', '201cm', '158cm', '162cm', '161cm', '160cm', '203cm',
       '157cm', '156cm', '202cm', '159cm', '206cm', '155cm'], dtype=object)

In [79]:
def convert_height(height):
  if "cm" in height:
    return int(height.strip("cm"))
  else:
    feet, inches = height.split("'")
    total_inches = int(feet)*12 + int(inches.strip('"'))
    return round(total_inches * 2.54)

#Apply function into height column
df1['Height'] = df1['Height'].apply(convert_height)
df1['Height'].unique()

array([170, 187, 188, 181, 175, 184, 191, 178, 193, 185, 199, 173, 168,
       176, 177, 183, 180, 189, 179, 195, 172, 182, 186, 192, 165, 194,
       167, 196, 163, 190, 174, 169, 171, 197, 200, 166, 164, 198, 201,
       158, 162, 161, 160, 203, 157, 156, 202, 159, 206, 155])

In [80]:
df1['Hits'].dtype

dtype('O')

In [81]:
df1['Hits'].unique()

array(['771', '562', '150', '207', '595', '248', '246', '120', '1.6K',
       '130', '321', '189', '175', '96', '118', '216', '212', '154',
       '205', '202', '339', '408', '103', '332', '86', '173', '161',
       '396', '1.1K', '433', '242', '206', '177', '1.5K', '198', '459',
       '117', '119', '209', '84', '187', '165', '203', '65', '336', '126',
       '313', '124', '145', '538', '182', '101', '45', '377', '99', '194',
       '403', '414', '593', '374', '245', '3.2K', '266', '299', '309',
       '215', '265', '211', '112', '337', '70', '159', '688', '116', '63',
       '144', '123', '71', '224', '113', '168', '61', '89', '137', '278',
       '75', '148', '176', '197', '264', '214', '247', '402', '440',
       '1.7K', '2.3K', '171', '320', '657', '87', '259', '200', '255',
       '253', '196', '60', '97', '85', '169', '256', '132', '239', '166',
       '121', '109', '32', '46', '122', '48', '527', '199', '282', '51',
       '1.9K', '642', '155', '323', '288', '497', '509', '79',

In [82]:

def convert_to_numeric(hits):
  if "K" in str(hits):
    return float(hits.strip("K")) * 1000
  else:
    return hits

# apply function to Hits column
df1['Hits'] = df1['Hits'].apply(convert_to_numeric)




In [83]:
df1['Hits']= df['Hits'].fillna(0)

In [84]:
def convert_to_numeric(hits):
  if "K" in str(hits):
    return float(hits.strip("K")) * 1000
  else:
    return hits

# apply function to Hits column
df1['Hits'] = df1['Hits'].apply(convert_to_numeric)

In [85]:
df1['Hits'].unique()

array(['771', '562', '150', '207', '595', '248', '246', '120', 1600.0,
       '130', '321', '189', '175', '96', '118', '216', '212', '154',
       '205', '202', '339', '408', '103', '332', '86', '173', '161',
       '396', 1100.0, '433', '242', '206', '177', 1500.0, '198', '459',
       '117', '119', '209', '84', '187', '165', '203', '65', '336', '126',
       '313', '124', '145', '538', '182', '101', '45', '377', '99', '194',
       '403', '414', '593', '374', '245', 3200.0, '266', '299', '309',
       '215', '265', '211', '112', '337', '70', '159', '688', '116', '63',
       '144', '123', '71', '224', '113', '168', '61', '89', '137', '278',
       '75', '148', '176', '197', '264', '214', '247', '402', '440',
       1700.0, 2300.0, '171', '320', '657', '87', '259', '200', '255',
       '253', '196', '60', '97', '85', '169', '256', '132', '239', '166',
       '121', '109', '32', '46', '122', '48', '527', '199', '282', '51',
       1900.0, '642', '155', '323', '288', '497', '509', '79',

In [86]:
df1['Hits'].dtype

dtype('O')

In [87]:
df1['Hits'] = df1['Hits'].astype('float')

In [88]:
df1['Hits'].dtype

dtype('float64')

In [89]:
df1['Hits'] = df1['Hits'].astype('int64')

In [90]:
df1['Hits'].dtype

dtype('int64')

In [91]:
df1['Hits'].unique()

array([ 771,  562,  150,  207,  595,  248,  246,  120, 1600,  130,  321,
        189,  175,   96,  118,  216,  212,  154,  205,  202,  339,  408,
        103,  332,   86,  173,  161,  396, 1100,  433,  242,  206,  177,
       1500,  198,  459,  117,  119,  209,   84,  187,  165,  203,   65,
        336,  126,  313,  124,  145,  538,  182,  101,   45,  377,   99,
        194,  403,  414,  593,  374,  245, 3200,  266,  299,  309,  215,
        265,  211,  112,  337,   70,  159,  688,  116,   63,  144,  123,
         71,  224,  113,  168,   61,   89,  137,  278,   75,  148,  176,
        197,  264,  214,  247,  402,  440, 1700, 2300,  171,  320,  657,
         87,  259,  200,  255,  253,  196,   60,   97,   85,  169,  256,
        132,  239,  166,  121,  109,   32,   46,  122,   48,  527,  199,
        282,   51, 1900,  642,  155,  323,  288,  497,  509,   79,   49,
        270,  511,   80,  128,  115,  156,  204,  143,  140,  152,  220,
        134,  225,   94,   74,  135,  142,   50,   

In [92]:
df1['A/W'].dtype

dtype('O')

In [93]:
df1['A/W'].unique()

array(['Medium', 'High', 'Low'], dtype=object)

In [94]:
df1['IR'].dtype

dtype('O')

In [95]:
df1['IR'].unique()

array(['5 ★', '3 ★', '4 ★', '2 ★', '1 ★'], dtype=object)

In [96]:
df1['IR'] = [int(rating.split()[0]) for rating in df1['IR']]

df1['IR'].unique()

array([5, 3, 4, 2, 1])

In [97]:
#Rename column from IR to IR_Star
df1 = df1.rename(columns={'IR':'IR_star'})
#df1.rename(columns={'old_column_name': 'new_column_name'},

In [98]:
df1['IR_star'].unique()

array([5, 3, 4, 2, 1])

In [99]:
df1['Interceptions'].dtype

dtype('int64')

In [100]:
df1['Interceptions'].unique()

array([40, 29, 19, 66, 36, 49, 55, 11, 38, 22, 90, 35, 87, 15, 30, 39, 88,
       24, 91, 82, 42, 27, 41, 79, 74, 58, 20, 85, 48, 83, 64, 21, 50, 81,
       78, 28, 86, 26, 34, 52, 37, 80, 25, 56, 23, 47, 45, 77, 84, 44, 53,
       18, 46, 72, 61, 89, 54, 63, 65, 73, 16, 32, 76, 59, 13, 70, 31, 69,
       33, 17, 75, 68, 60, 51, 71, 12, 57, 10, 43, 67, 14,  9, 62,  8,  7,
        6,  4,  5,  3])

In [101]:
df1['Joined'].dtype

dtype('O')

In [102]:
df1['Joined'].unique()

array(['1-Jul-04', '10-Jul-18', '16-Jul-14', ..., '22-Sep-18',
       '28-Feb-15', '6-Mar-18'], dtype=object)

In [103]:
# Convert 'Joined' column to datetime
df1['Joined'] = pd.to_datetime(df1['Joined'], format='%d-%b-%y', errors='coerce')

In [104]:
# Convert to string with date only
df1['Joined'] = df1['Joined'].dt.strftime('%Y-%m-%d')

In [105]:
df1['Joined'].unique()

array(['2004-07-01', '2018-07-10', '2014-07-16', ..., '2018-09-22',
       '2015-02-28', '2018-03-06'], dtype=object)

In [106]:
df1['Joined'].dtype

dtype('O')

In [107]:
df1['Jumping'].dtype

dtype('int64')

In [108]:
df1['Jumping'].unique()

array([68, 95, 78, 63, 62, 84, 69, 52, 77, 79, 90, 86, 87, 93, 57, 75, 66,
       82, 56, 32, 51, 76, 72, 81, 74, 71, 67, 65, 73, 64, 70, 80, 85, 37,
       89, 60, 49, 50, 83, 58, 53, 59, 88, 38, 92, 34, 61, 46, 43, 36, 91,
       39, 45, 42, 40, 54, 33, 55, 31, 44, 35, 47, 48, 30, 41, 94, 28, 29,
       27, 24, 19, 26, 17, 15, 22])

In [109]:
df1['Loan Date End'].dtype

dtype('O')

In [110]:
df1['Loan Date End'].unique()

array([nan, '30-Jun-21', '31-Dec-20', '30-Jan-21', '30-Jun-22',
       '31-May-21', '5-Jul-21', '31-Dec-21', '1-Jul-21', '1-Jan-21',
       '31-Aug-21', '31-Jan-21', '30-Dec-21', '23-Jun-21', '3-Jan-21',
       '27-Nov-21', '17-Jan-21', '30-Jun-23', '31-Jul-21', '22-Nov-20',
       '31-May-22', '30-Dec-20', '4-Jan-21', '30-Nov-20', '1-Aug-21'],
      dtype=object)

In [111]:
# Convert 'Joined' column to datetime
df1['Loan Date End'] = pd.to_datetime(df1['Loan Date End'], format='%d-%b-%y', errors='coerce')
df1['Loan Date End'] = df1['Loan Date End'].dt.strftime('%Y-%m-%d')

In [112]:
df1['Loan Date End'].unique()

array([nan, '2021-06-30', '2020-12-31', '2021-01-30', '2022-06-30',
       '2021-05-31', '2021-07-05', '2021-12-31', '2021-07-01',
       '2021-01-01', '2021-08-31', '2021-01-31', '2021-12-30',
       '2021-06-23', '2021-01-03', '2021-11-27', '2021-01-17',
       '2023-06-30', '2021-07-31', '2020-11-22', '2022-05-31',
       '2020-12-30', '2021-01-04', '2020-11-30', '2021-08-01'],
      dtype=object)

In [113]:
df1['Loan Date End'] = df1['Loan Date End'].fillna('0000-00-00')

In [114]:
df1['Loan Date End'].unique()

array(['0000-00-00', '2021-06-30', '2020-12-31', '2021-01-30',
       '2022-06-30', '2021-05-31', '2021-07-05', '2021-12-31',
       '2021-07-01', '2021-01-01', '2021-08-31', '2021-01-31',
       '2021-12-30', '2021-06-23', '2021-01-03', '2021-11-27',
       '2021-01-17', '2023-06-30', '2021-07-31', '2020-11-22',
       '2022-05-31', '2020-12-30', '2021-01-04', '2020-11-30',
       '2021-08-01'], dtype=object)

In [115]:
df1['Long Passing'].dtype

dtype('int64')

In [116]:
df1['Long Passing'].unique()

array([91, 77, 40, 93, 81, 70, 75, 44, 63, 86, 71, 84, 35, 59, 73, 83, 64,
       69, 79, 82, 68, 89, 76, 80, 87, 37, 65, 36, 50, 53, 78, 47, 74, 48,
       31, 85, 24, 55, 90, 54, 62, 32, 49, 66, 67, 51, 28, 46, 52, 72, 56,
       41, 45, 22, 88, 61, 33, 12, 60, 17, 27, 29, 23, 38, 16, 58, 34, 25,
       39, 21, 30, 42, 43, 57, 20, 26, 18, 19, 13, 15, 11, 14,  9, 10,  5,
        8])

In [117]:
df1['A/W'].dtype

dtype('O')

In [118]:
df1['A/W'].unique()

array(['Medium', 'High', 'Low'], dtype=object)

In [119]:
df1['Acceleration'].dtype

dtype('int64')

In [120]:
df1['Acceleration'].unique()

array([91, 87, 43, 77, 94, 56, 96, 38, 72, 95, 60, 42, 54, 79, 89, 64, 66,
       51, 73, 57, 80, 86, 85, 78, 40, 82, 76, 65, 68, 90, 48, 46, 88, 70,
       83, 84, 93, 52, 74, 92, 55, 58, 59, 67, 81, 62, 44, 71, 69, 50, 53,
       45, 49, 75, 41, 61, 63, 35, 47, 34, 36, 37, 39, 30, 97, 31, 33, 32,
       27, 28, 26, 29, 25, 17, 19, 24, 15, 23, 21, 20, 22, 16, 18, 13, 14])

In [121]:
df1['Long Shots'].dtype

dtype('int64')

In [122]:
df1['Long Shots'].unique()

array([94, 93, 12, 91, 84, 85, 14, 79, 10, 64, 78, 81, 17, 16, 65, 87, 18,
       86, 19, 15, 82, 63, 74, 76, 47, 89, 70, 90, 77, 13, 49, 54, 88, 80,
       53, 58, 51, 73, 66, 75, 83, 30, 46, 35, 71, 61, 72, 69, 43, 48, 62,
       41, 60, 11, 26, 57, 59, 68, 67,  7, 27, 56, 20, 52, 92, 50, 22, 40,
       39, 44, 31, 42,  9,  6, 55, 28, 23, 38, 24, 25, 34, 36, 29,  4,  8,
       45, 33, 37, 21, 32,  5])

In [123]:
df1['LongName'].dtype

dtype('O')

In [124]:
df1['LongName'].unique()

array(['Lionel Messi', 'C. Ronaldo dos Santos Aveiro', 'Jan Oblak', ...,
       'Ronan McKinley', "Zhen'ao Wang", 'Xiao Zhou'], dtype=object)

In [125]:
df1['Marking'].dtype

dtype('int64')

In [126]:
df1['Marking'].unique()

array([32, 28, 27, 68, 35, 38, 15, 34, 25, 93, 42, 84, 20, 17, 47, 85, 30,
       89, 82, 29, 56, 91, 72, 59, 79, 49, 83, 86, 50, 60, 94, 41, 57, 78,
       63, 88, 90,  9, 58, 74, 39, 92, 45, 36, 44, 87, 70, 76, 53, 80, 67,
       77, 12, 48, 55, 75, 81, 11, 64, 69, 14, 24, 52, 65, 19, 31, 13, 10,
       66, 71, 54, 46, 22, 40, 18, 51, 37, 43, 61, 26, 73, 21,  7, 33, 62,
       16, 23,  8,  6,  5,  4,  3])

In [127]:
df1['A/W'].dtype

dtype('O')

In [128]:
df1['A/W'].unique()

array(['Medium', 'High', 'Low'], dtype=object)

In [129]:
df1['Mentality'].dtype

dtype('int64')

In [130]:
df1['Mentality'].unique()

array([347, 353, 140, 408, 356, 391, 376, 341, 171, 358, 396, 122, 188,
       363, 414, 332, 386, 379, 348, 172, 382, 123, 294, 378, 313, 371,
       331, 412, 345, 377, 161, 306, 387, 339, 135, 360, 138, 369, 359,
       170, 361, 321, 397, 394, 385, 366, 162, 337, 362, 344, 319, 315,
       144, 336, 340, 373, 398, 324, 300, 338, 384, 139, 364, 372, 134,
       354, 342, 308, 322, 383, 263, 149, 304, 367, 357, 390, 291, 279,
       310, 388, 375, 349, 351, 365, 133, 334, 303, 380, 153, 392, 169,
       318, 350, 352, 401, 302, 325, 346, 132, 399, 281, 335, 403, 307,
       368, 141, 126, 328, 245, 131, 320, 127, 421, 400, 137, 374, 305,
        92, 316, 311, 120, 389, 145, 355, 148, 343, 142, 130, 121, 157,
       329, 323, 115, 150, 298, 154, 317, 295, 100, 301, 326, 327, 197,
       273, 287, 370, 290, 103, 393, 312, 297,  89, 271, 299, 124, 333,
       258, 309, 158, 272, 118, 314, 330, 292, 404, 101, 280, 277, 296,
       248, 285, 278, 109,  93, 146, 286, 284, 288, 105, 152, 11

In [131]:
df1['Movement'].dtype

dtype('int64')

In [132]:
df1['Movement'].unique()

array([451, 431, 307, 398, 453, 407, 460, 268, 458, 254, 354, 343, 284,
       286, 388, 378, 424, 464, 420, 399, 437, 322, 367, 272, 328, 448,
       332, 425, 435, 391, 434, 400, 331, 349, 429, 416, 312, 326, 418,
       419, 417, 386, 321, 409, 374, 304, 403, 351, 401, 365, 414, 292,
       323, 299, 433, 350, 348, 413, 320, 281, 427, 353, 364, 410, 428,
       316, 381, 442, 375, 288, 395, 385, 251, 319, 444, 383, 298, 411,
       412, 415, 393, 397, 443, 423, 387, 422, 327, 390, 362, 352, 406,
       277, 361, 421, 396, 384, 450, 338, 363, 359, 287, 297, 430, 382,
       377, 380, 438, 449, 257, 371, 339, 341, 404, 345, 394, 295, 246,
       265, 258, 366, 294, 314, 266, 405, 218, 337, 267, 220, 376, 309,
       283, 426, 347, 244, 240, 291, 340, 250, 305, 290, 317, 334, 355,
       333, 389, 330, 318, 441, 402, 344, 335, 219, 264, 408, 274, 373,
       379, 256, 229, 392, 372, 360, 262, 346, 278, 248, 368, 279, 269,
       336, 342, 236, 370, 243, 315, 249, 227, 329, 239, 369, 22

In [133]:
df['Age'].dtype

dtype('int64')

In [134]:
df1['Age'].unique()

array([33, 35, 27, 29, 28, 31, 21, 34, 32, 25, 26, 30, 20, 24, 22, 23, 19,
       38, 42, 36, 37, 18, 17, 39, 40, 41, 16, 43, 53])

In [135]:
df1['Nationality'].dtype

dtype('O')

In [136]:
df1['Nationality'].unique()

array(['Argentina', 'Portugal', 'Slovenia', 'Belgium', 'Brazil', 'Poland',
       'Egypt', 'France', 'Germany', 'Netherlands', 'Senegal', 'Spain',
       'England', 'Scotland', 'Korea Republic', 'Costa Rica', 'Italy',
       'Gabon', 'Croatia', 'Uruguay', 'Switzerland', 'Serbia', 'Slovakia',
       'Morocco', 'Algeria', 'Denmark', 'Hungary', 'Bosnia Herzegovina',
       'Nigeria', 'Cameroon', 'Norway', 'Ghana', 'Mexico', 'Austria',
       'Albania', 'Colombia', 'Chile', 'Ivory Coast', 'Greece', 'Finland',
       'Wales', 'Sweden', 'Togo', 'Czech Republic', 'Russia', 'Venezuela',
       'Canada', 'United States', 'Guinea', 'Montenegro', 'Israel',
       'Republic of Ireland', 'Ukraine', 'Turkey', 'Ecuador', 'Jamaica',
       'DR Congo', 'Australia', 'China PR', 'Armenia', 'Northern Ireland',
       'North Macedonia', 'Kosovo', 'Mali', 'Peru',
       'Central African Republic', 'Iceland', 'Burkina Faso', 'Paraguay',
       'Japan', 'Romania', 'New Zealand', 'Iran', 'Angola', 'Tunisia',
 

In [137]:
df1['PAC'].dtype

dtype('int64')

In [138]:
df1['PAC'].unique()

array([85, 89, 87, 76, 91, 78, 93, 86, 96, 88, 94, 65, 84, 74, 71, 77, 68,
       75, 54, 79, 83, 80, 81, 82, 63, 67, 90, 66, 42, 73, 70, 64, 57, 58,
       69, 72, 50, 59, 92, 60, 62, 55, 52, 56, 61, 53, 45, 37, 95, 43, 44,
       46, 48, 49, 47, 34, 39, 40, 51, 41, 36, 32, 33, 30, 31, 38, 35, 28,
       29, 25])

In [139]:
df1['PAS'].dtype

dtype('int64')

In [140]:
df1['PAS'].unique()

array([91, 81, 78, 93, 86, 85, 88, 71, 80, 76, 74, 77, 79, 84, 73, 55, 83,
       87, 72, 75, 58, 89, 82, 68, 67, 64, 66, 59, 69, 90, 65, 53, 63, 62,
       70, 56, 42, 54, 61, 57, 60, 48, 52, 47, 46, 44, 45, 50, 51, 49, 43,
       36, 38, 40, 41, 35, 39, 34, 33, 37, 30, 32, 29, 31, 26, 28, 25, 27])

In [141]:
df1['↓OVA'].dtype

dtype('int64')

In [142]:
df1['↓OVA'].unique()

array([93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77,
       76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60,
       59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47])

In [143]:
df1['PHY'].dtype

dtype('int64')

In [144]:
df1['PHY'].unique()

array([65, 77, 90, 78, 59, 82, 75, 91, 76, 88, 86, 85, 73, 67, 79, 63, 83,
       89, 66, 69, 72, 64, 71, 81, 87, 68, 84, 80, 55, 70, 44, 62, 51, 57,
       60, 58, 56, 74, 52, 61, 53, 45, 50, 54, 47, 48, 49, 42, 37, 40, 39,
       43, 38, 46, 41, 34, 35, 36, 31, 32, 33, 29, 28])

In [145]:
df1['POT'].dtype

dtype('int64')

In [146]:
df1['POT'].unique()

array([93, 92, 91, 90, 95, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78,
       77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61,
       60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47])

In [147]:
df1['Base Stats'].dtype

dtype('int64')

In [148]:
df1['Base Stats'].unique()

array([466, 464, 489, 485, 451, 457, 470, 490, 484, 455, 469, 463, 468,
       497, 442, 439, 473, 452, 498, 449, 477, 401, 446, 447, 465, 430,
       461, 422, 476, 460, 453, 467, 471, 399, 424, 441, 459, 438, 437,
       454, 428, 445, 431, 474, 421, 435, 448, 475, 403, 444, 443, 419,
       405, 420, 423, 396, 388, 482, 478, 385, 394, 480, 433, 450, 462,
       456, 436, 434, 429, 400, 440, 425, 410, 458, 398, 413, 373, 406,
       408, 472, 426, 407, 432, 427, 415, 481, 417, 372, 380, 418, 383,
       414, 409, 412, 411, 386, 362, 402, 390, 404, 391, 416, 375, 389,
       361, 397, 366, 392, 393, 382, 368, 387, 352, 376, 384, 378, 379,
       341, 354, 369, 395, 357, 381, 377, 344, 360, 370, 338, 333, 367,
       363, 349, 355, 345, 358, 348, 374, 351, 343, 342, 353, 321, 350,
       365, 364, 371, 327, 331, 359, 347, 356, 339, 319, 317, 335, 346,
       329, 315, 324, 322, 325, 332, 336, 337, 330, 316, 313, 306, 307,
       328, 310, 340, 308, 318, 334, 301, 289, 302, 320, 323, 32

In [149]:
df1['Name'].dtype

dtype('O')

In [150]:
df1['Name'].unique()

array(['L. Messi', 'Cristiano Ronaldo', 'J. Oblak', ..., 'R. McKinley',
       "Wang Zhen'ao", 'Zhou Xiao'], dtype=object)

In [151]:
df1['Value'].dtype

dtype('O')

In [152]:
df1['Value'].unique()

array(['€103.5M', '€63M', '€120M', '€129M', '€132M', '€111M', '€120.5M',
       '€102M', '€185.5M', '€110M', '€113M', '€90.5M', '€82M', '€17.5M',
       '€83.5M', '€33.5M', '€114.5M', '€78M', '€103M', '€109M', '€92M',
       '€10M', '€76.5M', '€89.5M', '€87.5M', '€79.5M', '€124M', '€114M',
       '€95M', '€92.5M', '€105.5M', '€88.5M', '€85M', '€81.5M', '€26M',
       '€21M', '€56M', '€67.5M', '€53M', '€36.5M', '€51M', '€65.5M',
       '€46.5M', '€61.5M', '€72.5M', '€77.5M', '€43.5M', '€32.5M', '€36M',
       '€32M', '€54M', '€49.5M', '€57M', '€66.5M', '€74.5M', '€71.5M',
       '€121M', '€99M', '€67M', '€86.5M', '€93.5M', '€70M', '€62M',
       '€66M', '€58M', '€44M', '€81M', '€37M', '€14.5M', '€46M', '€47.5M',
       '€52.5M', '€54.5M', '€34.5M', '€57.5M', '€51.5M', '€44.5M', '€55M',
       '€48M', '€60.5M', '€63.5M', '€61M', '€29M', '€58.5M', '€55.5M',
       '€42M', '€40.5M', '€43M', '€45.5M', '€34M', '€26.5M', '€42.5M',
       '€35.5M', '€45M', '€41.5M', '€40M', '€11M', '€13.5M', '

In [153]:
#df1['Value'] = df1['Value'].replace({'€': '', 'M': '000000', 'K': '000'}, regex=True).map(pd.eval).astype(float)
# Function to convert Euro currency format to numeric values
def convert_currency(value):
    if 'M' in value:
        return float(value.replace('€', '').replace('M', '')) * 1000000
    elif 'K' in value:
        return float(value.replace('€', '').replace('K', '')) * 1000
    else:
        return float(value.replace('€', ''))

# Apply the conversion function to the 'Value' column
df1['Value'] = df1['Value'].apply(convert_currency)

In [154]:
df1['Value'][0]

103500000.0

In [155]:
df1['playerUrl'].dtype

dtype('O')

In [156]:
df1['playerUrl'].unique()

array(['http://sofifa.com/player/158023/lionel-messi/210006/',
       'http://sofifa.com/player/20801/c-ronaldo-dos-santos-aveiro/210006/',
       'http://sofifa.com/player/200389/jan-oblak/210006/', ...,
       'http://sofifa.com/player/252757/ronan-mckinley/210006/',
       'http://sofifa.com/player/243790/zhenao-wang/210006/',
       'http://sofifa.com/player/252520/xiao-zhou/210006/'], dtype=object)

In [157]:
df1.head()

ID               Name                      LongName  \
0  158023           L. Messi                  Lionel Messi   
1   20801  Cristiano Ronaldo  C. Ronaldo dos Santos Aveiro   
2  200389           J. Oblak                     Jan Oblak   
3  192985       K. De Bruyne               Kevin De Bruyne   
4  190871          Neymar Jr    Neymar da Silva Santos Jr.   

                                           photoUrl  \
0  https://cdn.sofifa.com/players/158/023/21_60.png   
1  https://cdn.sofifa.com/players/020/801/21_60.png   
2  https://cdn.sofifa.com/players/200/389/21_60.png   
3  https://cdn.sofifa.com/players/192/985/21_60.png   
4  https://cdn.sofifa.com/players/190/871/21_60.png   

                                           playerUrl Nationality  Age  ↓OVA  \
0  http://sofifa.com/player/158023/lionel-messi/2...   Argentina   33    93   
1  http://sofifa.com/player/20801/c-ronaldo-dos-s...    Portugal   35    92   
2  http://sofifa.com/player/200389/jan-oblak/210006/    Slovenia   27    91   
3  http://sofifa.com/player/192985/kevin-de-bruyn...     Belgium   29    91   
4  http://sofifa.com/player/190871/neymar-da-silv...      Brazil   28    91   

   POT                 Club     Contract   Positions  Height Weight  \
0   93         FC Barcelona  2004 ~ 2021  RW, ST, CF     170   72kg   
1   92             Juventus  2018 ~ 2022      ST, LW     187   83kg   
2   93      Atlético Madrid  2014 ~ 2023          GK     188   87kg   
3   91      Manchester City  2015 ~ 2023     CAM, CM     181   70kg   
4   91  Paris Saint-Germain  2017 ~ 2022     LW, CAM     175   68kg   

  Preferred Foot  BOV Best Position      Joined Loan Date End        Value  \
0           Left   93            RW  2004-07-01    0000-00-00  103500000.0   
1          Right   92            ST  2018-07-10    0000-00-00   63000000.0   
2          Right   91            GK  2014-07-16    0000-00-00  120000000.0   
3          Right   91           CAM  2015-08-30    0000-00-00  129000000.0   
4          Right   91            LW  2017-08-03    0000-00-00  132000000.0   

    Wage Release Clause  Attacking  Crossing  Finishing  Heading Accuracy  \
0  €560K        €138.4M        429        85         95                70   
1  €220K         €75.9M        437        84         95                90   
2  €125K        €159.4M         95        13         11                15   
3  €370K          €161M        407        94         82                55   
4  €270K        €166.5M        408        85         87                62   

   Short Passing  Volleys  Skill  Dribbling  Curve  FK Accuracy  Long Passing  \
0             91       88    470         96     93           94            91   
1             82       86    414         88     81           76            77   
2             43       13    109         12     13           14            40   
3             94       82    441         88     85           83            93   
4             87       87    448         95     88           89            81   

   Ball Control  Movement  Acceleration  Sprint Speed  Agility  Reactions  \
0            96       451            91            80       91         94   
1            92       431            87            91       87         95   
2            30       307            43            60       67         88   
3            92       398            77            76       78         91   
4            95       453            94            89       96         91   

   Balance  Power  Shot Power  Jumping  Stamina  Strength  Long Shots  \
0       95    389          86       68       72        69          94   
1       71    444          94       95       84        78          93   
2       49    268          59       78       41        78          12   
3       76    408          91       63       89        74          91   
4       83    357          80       62       81        50          84   

   Mentality  Aggression  Interceptions  Positioning  Vision  Penalties  \
0    

In [158]:
df1['W/F'].dtype

dtype('O')

In [159]:
df1['W/F'].unique()

array(['4 ★', '3 ★', '5 ★', '2 ★', '1 ★'], dtype=object)

In [160]:
df1['W/F'] = df1['W/F'].str.split(' ').str[0]

In [161]:
df1['W/F'].unique()

array(['4', '3', '5', '2', '1'], dtype=object)

In [162]:
df1['SM'].dtype

dtype('O')

In [163]:
df1['SM'].unique()

array(['4★', '5★', '1★', '2★', '3★'], dtype=object)

In [164]:
df1['SM'].unique()

array(['4★', '5★', '1★', '2★', '3★'], dtype=object)

In [165]:

# The str.extract method with the regex pattern (\d) extracts the numeric part from each value in the 'SM' column.
df1['SM'] = df1['SM'].str.extract(r'(\d)').astype(int)



In [166]:
df1['SM'].unique()

array([4, 5, 1, 2, 3])

In [167]:
df1['Weight'].dtype

dtype('O')

In [168]:
df1['Weight'].unique()

array(['72kg', '83kg', '87kg', '70kg', '68kg', '80kg', '71kg', '91kg',
       '73kg', '85kg', '92kg', '69kg', '84kg', '96kg', '81kg', '82kg',
       '75kg', '86kg', '89kg', '74kg', '76kg', '64kg', '78kg', '90kg',
       '66kg', '60kg', '94kg', '79kg', '67kg', '65kg', '59kg', '61kg',
       '93kg', '88kg', '97kg', '77kg', '62kg', '63kg', '95kg', '100kg',
       '58kg', '183lbs', '179lbs', '172lbs', '196lbs', '176lbs', '185lbs',
       '170lbs', '203lbs', '168lbs', '161lbs', '146lbs', '130lbs',
       '190lbs', '174lbs', '148lbs', '165lbs', '159lbs', '192lbs',
       '181lbs', '139lbs', '154lbs', '157lbs', '163lbs', '98kg', '103kg',
       '99kg', '102kg', '56kg', '101kg', '57kg', '55kg', '104kg', '107kg',
       '110kg', '53kg', '50kg', '54kg', '52kg'], dtype=object)

In [169]:
"""
def convert_weight(weight):
    if 'kg' in weight:
        return float(weight.replace('kg', ''))
    elif 'lbs' in weight:
        return float(weight.replace('lbs', '')) * 0.453592
    else:
        return None
"""
def convert_weight(weight):
    if 'kg' in weight:
        return float(weight.replace('kg',''))
    elif 'lbs' in weight:
        return float(weight.replace('lbs',''))* 0.453
    else:
        return None
df1['Weight'] = df1['Weight'].apply(convert_weight)



In [170]:
df1['Weight'] = round(df1['Weight'],2)

In [171]:
df1['Weight'].unique()

array([ 72.  ,  83.  ,  87.  ,  70.  ,  68.  ,  80.  ,  71.  ,  91.  ,
        73.  ,  85.  ,  92.  ,  69.  ,  84.  ,  96.  ,  81.  ,  82.  ,
        75.  ,  86.  ,  89.  ,  74.  ,  76.  ,  64.  ,  78.  ,  90.  ,
        66.  ,  60.  ,  94.  ,  79.  ,  67.  ,  65.  ,  59.  ,  61.  ,
        93.  ,  88.  ,  97.  ,  77.  ,  62.  ,  63.  ,  95.  , 100.  ,
        58.  ,  82.9 ,  81.09,  77.92,  88.79,  79.73,  83.8 ,  77.01,
        91.96,  76.1 ,  72.93,  66.14,  58.89,  86.07,  78.82,  67.04,
        74.74,  72.03,  86.98,  81.99,  62.97,  69.76,  71.12,  73.84,
        98.  , 103.  ,  99.  , 102.  ,  56.  , 101.  ,  57.  ,  55.  ,
       104.  , 107.  , 110.  ,  53.  ,  50.  ,  54.  ,  52.  ])